In [1]:
dseb65b='''Bùi Thị Lan  Anh
Nguyễn Thị Mai  Anh
Nguyễn Thị Vân  Anh
Phạm Đức  Anh
Trương Đức  Anh
Phạm Thị Ngọc  Ánh
Doãn Quốc  Bảo
Nguyễn Mạnh  Cường
Nguyễn Danh  Dũng
Phạm Khánh  Dương
Nguyễn Trần Quốc  Đạt
Nguyễn Thị Hương  Giang
Trần Thu  Hiền
Trịnh Minh  Hiếu
Đặng Ngọc  Hòa
Bùi Huỳnh Gia  Huy
Bùi Việt  Huy
Đỗ Công  Huy
Nguyễn Khánh  Huyền
Lê Lan  Hương
Nguyễn Văn  Khôi
Nguyễn Trần Tuấn  Kiệt
Đoàn Tùng  Lâm
Đào Khánh  Linh
Đỗ Hà  Linh
Phạm Khánh  Linh
Lý Thành  Long
Phạm Thành  Long
Hà Quang  Minh
Nguyễn Đăng  Minh
Nguyễn Thanh  Mơ
Phạm Minh Bảo  Ngọc
Nguyễn Hồng  Nhung
Ngô Hoàng  Phúc
Bùi Minh  Phương
Nguyễn Thị Hà  Phương
Thiều Diệu  Thúy
Dương Thị Huyền  Trang
Ninh Duy  Tuân
Trần Anh  Tuấn
Vũ Bùi Đình  Tùng'''
name_list = dseb65b.split('\n')
import random

In [4]:
print(random.choices(name_list,k=1))

['Nguyễn Văn  Khôi']


In [6]:
import json 
numbers = {'a':[1,2,3,5],'b':2}
with open('aset.json','w') as file:
    json.dump(numbers,file)
with open('aset.json','r') as file:
    content = json.load(file)
print(content)

{'a': [1, 2, 3, 5], 'b': 2}


## Numpy

In [7]:
import numpy as np 
np.array([12,3,1,2,3,2,4])

array([12,  3,  1,  2,  3,  2,  4])

In [11]:
np.array([2,3,1,2,3,2,4], dtype=np.int8)


array([2, 3, 1, 2, 3, 2, 4], dtype=int8)

In [13]:
type(np.zeros((2,3)))

numpy.ndarray

In [14]:
np.ones((3,3))

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [16]:
np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [20]:
a = np.full((2,3),-1)

In [19]:
x= np.arange(1,20,2)

In [21]:
x.ndim

1

In [22]:
a.ndim

2

In [23]:
x.shape

(10,)

In [24]:
a.shape

(2, 3)

In [25]:
a.size 

6

In [26]:
a.dtype

dtype('int64')

In [28]:
b =np.full((2,3),-1,dtype=np.int8)
b.dtype

dtype('int8')

In [29]:
a.nbytes

48

In [30]:
b.nbytes

6

In [31]:
x = np.array([1,2,3],dtype=np.int8)

In [33]:
x[1] = 3.14
print(x)  

[1 3 3]


In [36]:
a  = np.full((4,5),1)
print(a)

[[1 1 1 1 1]
 [1 1 1 1 1]
 [1 1 1 1 1]
 [1 1 1 1 1]]


In [38]:
a_sub = a[:2,:2]
print(a_sub)

[[1 1]
 [1 1]]


In [39]:
a_sub[0,0]=99
print(a_sub)
print(a)

[[99  1]
 [ 1  1]]
[[99  1  1  1  1]
 [ 1  1  1  1  1]
 [ 1  1  1  1  1]
 [ 1  1  1  1  1]]


In [40]:
b = np.arange(0,30)

In [41]:
b 

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29])

In [43]:
a = b.reshape(6,5)
a  

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24],
       [25, 26, 27, 28, 29]])

In [45]:
c = b.reshape(3,2,5)
c[0,0,0] =999
print(b)
print(a) 


[999   1   2   3   4   5   6   7   8   9  10  11  12  13  14  15  16  17
  18  19  20  21  22  23  24  25  26  27  28  29]
[[999   1   2   3   4]
 [  5   6   7   8   9]
 [ 10  11  12  13  14]
 [ 15  16  17  18  19]
 [ 20  21  22  23  24]
 [ 25  26  27  28  29]]


In [47]:
b.reshape(-1,5,3)

array([[[999,   1,   2],
        [  3,   4,   5],
        [  6,   7,   8],
        [  9,  10,  11],
        [ 12,  13,  14]],

       [[ 15,  16,  17],
        [ 18,  19,  20],
        [ 21,  22,  23],
        [ 24,  25,  26],
        [ 27,  28,  29]]])

In [48]:
a 

array([[999,   1,   2,   3,   4],
       [  5,   6,   7,   8,   9],
       [ 10,  11,  12,  13,  14],
       [ 15,  16,  17,  18,  19],
       [ 20,  21,  22,  23,  24],
       [ 25,  26,  27,  28,  29]])

In [49]:
a.flatten()

array([999,   1,   2,   3,   4,   5,   6,   7,   8,   9,  10,  11,  12,
        13,  14,  15,  16,  17,  18,  19,  20,  21,  22,  23,  24,  25,
        26,  27,  28,  29])

In [50]:
print(c)

[[[999   1   2   3   4]
  [  5   6   7   8   9]]

 [[ 10  11  12  13  14]
  [ 15  16  17  18  19]]

 [[ 20  21  22  23  24]
  [ 25  26  27  28  29]]]


In [51]:
c.flatten()

array([999,   1,   2,   3,   4,   5,   6,   7,   8,   9,  10,  11,  12,
        13,  14,  15,  16,  17,  18,  19,  20,  21,  22,  23,  24,  25,
        26,  27,  28,  29])