## Lecture 13

In [1]:
import numpy as np

In [16]:
arr = np.arange(1e6, dtype=np.int8)
arr.nbytes

1000000

In [18]:
arr = np.arange(1e6)
arr.nbytes

8000000

In [23]:
arr1 = np.full((2,4),1)
arr2 = np.full((2,4),2)
print(arr1)
print(arr2)

[[1 1 1 1]
 [1 1 1 1]]
[[2 2 2 2]
 [2 2 2 2]]


In [24]:
np.concatenate([arr1,arr2], axis = 0)

array([[1, 1, 1, 1],
       [1, 1, 1, 1],
       [2, 2, 2, 2],
       [2, 2, 2, 2]])

In [25]:
np.concatenate([arr1,arr2], axis = 1)

array([[1, 1, 1, 1, 2, 2, 2, 2],
       [1, 1, 1, 1, 2, 2, 2, 2]])

In [26]:
np.concatenate([arr1,arr2])

array([[1, 1, 1, 1],
       [1, 1, 1, 1],
       [2, 2, 2, 2],
       [2, 2, 2, 2]])

In [27]:
np.vstack([arr1,arr2])# np.concatenate(axis=0)

array([[1, 1, 1, 1],
       [1, 1, 1, 1],
       [2, 2, 2, 2],
       [2, 2, 2, 2]])

In [28]:
np.hstack([arr1,arr2]) # np.concatenate(axis=1)

array([[1, 1, 1, 1, 2, 2, 2, 2],
       [1, 1, 1, 1, 2, 2, 2, 2]])

In [29]:
arr = np.arange(20).reshape(2,10)
arr 

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19]])

In [31]:
np.split(arr,2, axis = 0)

[array([[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]]),
 array([[10, 11, 12, 13, 14, 15, 16, 17, 18, 19]])]

In [34]:
np.split(arr,5, axis = 1)

[array([[ 0,  1],
        [10, 11]]),
 array([[ 2,  3],
        [12, 13]]),
 array([[ 4,  5],
        [14, 15]]),
 array([[ 6,  7],
        [16, 17]]),
 array([[ 8,  9],
        [18, 19]])]

In [35]:
np.split(arr,5, axis = 1)

[array([[ 0,  1],
        [10, 11]]),
 array([[ 2,  3],
        [12, 13]]),
 array([[ 4,  5],
        [14, 15]]),
 array([[ 6,  7],
        [16, 17]]),
 array([[ 8,  9],
        [18, 19]])]

In [36]:
np.split(arr,[5], axis = 1)

[array([[ 0,  1,  2,  3,  4],
        [10, 11, 12, 13, 14]]),
 array([[ 5,  6,  7,  8,  9],
        [15, 16, 17, 18, 19]])]

In [37]:
np.split(arr,[2,5,7], axis = 1)

[array([[ 0,  1],
        [10, 11]]),
 array([[ 2,  3,  4],
        [12, 13, 14]]),
 array([[ 5,  6],
        [15, 16]]),
 array([[ 7,  8,  9],
        [17, 18, 19]])]

In [38]:
big_arr =np.arange(1e6) 


In [40]:
%timeit sum(big_arr)

92.2 ms ± 4.92 ms per loop (mean ± std. dev. of 7 runs, 10 loops each)


In [41]:
%timeit np.sum(big_arr)

1.85 ms ± 28.8 μs per loop (mean ± std. dev. of 7 runs, 1,000 loops each)


In [46]:
a = np.array([1,2,3])
b = np.array([[1],[3]])
print(a.shape, b.shape)
a+b 

(3,) (2, 1)


array([[2, 3, 4],
       [4, 5, 6]])

In [47]:
np.random.seed(0)
x = np.random.randint(10,size=(3,4))
print(x)

[[5 0 3 3]
 [7 9 3 5]
 [2 4 7 6]]


In [49]:
#1 
np.sum(x>8)

np.int64(1)

In [50]:
x==3 #mask or boolean index

array([[False, False,  True,  True],
       [False, False,  True, False],
       [False, False, False, False]])

In [52]:
#2
np.sum(x==3)

np.int64(3)

In [54]:
#3
np.sum(x[x>3])

np.int64(43)

In [57]:
#4
x[x%2==1].prod()

np.int64(297675)

In [58]:
#5
from our_module import is_prime

In [76]:
x.flatten()[list(map(is_prime,x.flatten()))].sum()

np.int64(35)

In [79]:
x[np.array(list(map(is_prime,x.flatten()))).reshape(x.shape)].sum()

np.int64(35)

In [84]:
#6
np.sum(x<6, axis=1)

array([4, 2, 2])

In [86]:
np.random.seed(0)
A = np.random.randint(100,size=(6,8))
A 

array([[44, 47, 64, 67, 67,  9, 83, 21],
       [36, 87, 70, 88, 88, 12, 58, 65],
       [39, 87, 46, 88, 81, 37, 25, 77],
       [72,  9, 20, 80, 69, 79, 47, 64],
       [82, 99, 88, 49, 29, 19, 19, 14],
       [39, 32, 65,  9, 57, 32, 31, 74]], dtype=int32)

In [87]:
# Sum of the number (produtct of two primes)

In [89]:
k = min(A.shape)
A[range(k),range(k)]

array([44, 87, 46, 80, 29, 32], dtype=int32)

In [90]:
A[:k,:k] # slicing, not fancy index

array([[44, 47, 64, 67, 67,  9],
       [36, 87, 70, 88, 88, 12],
       [39, 87, 46, 88, 81, 37],
       [72,  9, 20, 80, 69, 79],
       [82, 99, 88, 49, 29, 19],
       [39, 32, 65,  9, 57, 32]], dtype=int32)

In [91]:
A 

array([[44, 47, 64, 67, 67,  9, 83, 21],
       [36, 87, 70, 88, 88, 12, 58, 65],
       [39, 87, 46, 88, 81, 37, 25, 77],
       [72,  9, 20, 80, 69, 79, 47, 64],
       [82, 99, 88, 49, 29, 19, 19, 14],
       [39, 32, 65,  9, 57, 32, 31, 74]], dtype=int32)

In [95]:
A[range(k),range(A.shape[1]-A.shape[0],A.shape[1])[::-1]]

array([21, 58, 37, 69, 49, 65], dtype=int32)

In [93]:
A.shape[1]-A.shape[0]

2

In [94]:
A.shape[1]

8

In [97]:
B = np.arange(12).reshape(3,4)
C = np.arange(8).reshape(4,2)


In [98]:
B*B 

array([[  0,   1,   4,   9],
       [ 16,  25,  36,  49],
       [ 64,  81, 100, 121]])

In [99]:
B.dot(C)

array([[ 28,  34],
       [ 76,  98],
       [124, 162]])

In [102]:
D=np.arange(16).reshape(4,4)
print(D)
np.diagonal(D)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]


array([ 0,  5, 10, 15])

In [103]:
np.diagonal(A)

array([44, 87, 46, 80, 29, 32], dtype=int32)

In [104]:
np.linalg.det(D)

np.float64(0.0)

In [106]:
a = np.array([[10,40],[30,20]])
print(a)

[[10 40]
 [30 20]]


In [108]:
a = np.array([[10,40],[30,20]])
print(a)
np.sort(a,axis=0)

[[10 40]
 [30 20]]


array([[10, 20],
       [30, 40]])

In [109]:
print(a)
np.sort(a,axis=1)

[[10 40]
 [30 20]]


array([[10, 40],
       [20, 30]])

In [110]:
print(a)
np.sort(a,axis=None)

[[10 40]
 [30 20]]


array([10, 20, 30, 40])

In [111]:
A 

array([[44, 47, 64, 67, 67,  9, 83, 21],
       [36, 87, 70, 88, 88, 12, 58, 65],
       [39, 87, 46, 88, 81, 37, 25, 77],
       [72,  9, 20, 80, 69, 79, 47, 64],
       [82, 99, 88, 49, 29, 19, 19, 14],
       [39, 32, 65,  9, 57, 32, 31, 74]], dtype=int32)

In [112]:
np.sort(A,axis=1)

array([[ 9, 21, 44, 47, 64, 67, 67, 83],
       [12, 36, 58, 65, 70, 87, 88, 88],
       [25, 37, 39, 46, 77, 81, 87, 88],
       [ 9, 20, 47, 64, 69, 72, 79, 80],
       [14, 19, 19, 29, 49, 82, 88, 99],
       [ 9, 31, 32, 32, 39, 57, 65, 74]], dtype=int32)

In [116]:
print(A)
np.partition(A,3, axis=1)

[[44 47 64 67 67  9 83 21]
 [36 87 70 88 88 12 58 65]
 [39 87 46 88 81 37 25 77]
 [72  9 20 80 69 79 47 64]
 [82 99 88 49 29 19 19 14]
 [39 32 65  9 57 32 31 74]]


array([[ 9, 21, 44, 47, 64, 67, 67, 83],
       [12, 36, 58, 65, 70, 87, 88, 88],
       [25, 37, 39, 46, 77, 81, 87, 88],
       [ 9, 20, 47, 64, 69, 72, 79, 80],
       [14, 19, 19, 29, 49, 82, 88, 99],
       [ 9, 31, 32, 32, 39, 57, 65, 74]], dtype=int32)

array([[1, 1, 1, 1],
       [1, 1, 1, 1]])

In [118]:
x =np.array([2,3,1,8,3,1])
np.partition(x,2)

array([1, 1, 2, 3, 3, 8])

In [119]:
x 

array([2, 3, 1, 8, 3, 1])

In [120]:
x.argsort()

array([2, 5, 0, 1, 4, 3])

In [121]:
x[x.argsort()]

array([1, 1, 2, 3, 3, 8])

In [122]:
x[x.argsort()[:3]]

array([1, 1, 2])

In [123]:
#Sum top 3 min entry on each rows of A
A


array([[44, 47, 64, 67, 67,  9, 83, 21],
       [36, 87, 70, 88, 88, 12, 58, 65],
       [39, 87, 46, 88, 81, 37, 25, 77],
       [72,  9, 20, 80, 69, 79, 47, 64],
       [82, 99, 88, 49, 29, 19, 19, 14],
       [39, 32, 65,  9, 57, 32, 31, 74]], dtype=int32)

In [125]:
a = np.arange(10)
a[range(1,10,2)]


array([1, 3, 5, 7, 9])

In [131]:
b= np.arange(1,10).reshape(3,3)
print(b)
np.diagonal(b)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


array([1, 5, 9])

In [144]:
c = np.arange(10,101,10)
c[range(0,10,2)]


array([10, 30, 50, 70, 90])

In [141]:
a = np.random.randint(10,101, size=10)
print(a)
np.sort(a)

[88 25 30 68 33 89 23 95 58 59]


array([23, 25, 30, 33, 58, 59, 68, 88, 89, 95], dtype=int32)

In [148]:
b = np.random.randint(100,size=(3,3))
print(b)
print(np.sort(b, axis = 1))
print(np.sort(b, axis = 0))


[[62 35 94]
 [67 82 46]
 [99 20 81]]
[[35 62 94]
 [46 67 82]
 [20 81 99]]
[[62 20 46]
 [67 35 81]
 [99 82 94]]


In [152]:
c = np.random.randint(100, size = 10)
c
np.sort(c)[::-1]

array([80, 56, 54, 51, 46, 42, 38, 32, 19,  0], dtype=int32)

In [153]:
c.argsort()

array([4, 6, 2, 5, 8, 7, 0, 3, 9, 1])

In [155]:
print(A)
A.argsort(axis=1)

[[44 47 64 67 67  9 83 21]
 [36 87 70 88 88 12 58 65]
 [39 87 46 88 81 37 25 77]
 [72  9 20 80 69 79 47 64]
 [82 99 88 49 29 19 19 14]
 [39 32 65  9 57 32 31 74]]


array([[5, 7, 0, 1, 2, 3, 4, 6],
       [5, 0, 6, 7, 2, 1, 3, 4],
       [6, 5, 0, 2, 7, 4, 1, 3],
       [1, 2, 6, 7, 4, 0, 5, 3],
       [7, 5, 6, 4, 3, 0, 2, 1],
       [3, 6, 5, 1, 0, 4, 2, 7]])

In [156]:
c.argsort()[::-1]

array([1, 9, 3, 0, 7, 8, 5, 2, 6, 4])