## Lecture 13

In [1]:
import numpy as np

In [16]:
arr = np.arange(1e6, dtype=np.int8)
arr.nbytes

1000000

In [18]:
arr = np.arange(1e6)
arr.nbytes

8000000

In [23]:
arr1 = np.full((2,4),1)
arr2 = np.full((2,4),2)
print(arr1)
print(arr2)

[[1 1 1 1]
 [1 1 1 1]]
[[2 2 2 2]
 [2 2 2 2]]


In [24]:
np.concatenate([arr1,arr2], axis = 0)

array([[1, 1, 1, 1],
       [1, 1, 1, 1],
       [2, 2, 2, 2],
       [2, 2, 2, 2]])

In [25]:
np.concatenate([arr1,arr2], axis = 1)

array([[1, 1, 1, 1, 2, 2, 2, 2],
       [1, 1, 1, 1, 2, 2, 2, 2]])

In [26]:
np.concatenate([arr1,arr2])

array([[1, 1, 1, 1],
       [1, 1, 1, 1],
       [2, 2, 2, 2],
       [2, 2, 2, 2]])

In [27]:
np.vstack([arr1,arr2])# np.concatenate(axis=0)

array([[1, 1, 1, 1],
       [1, 1, 1, 1],
       [2, 2, 2, 2],
       [2, 2, 2, 2]])

In [28]:
np.hstack([arr1,arr2]) # np.concatenate(axis=1)

array([[1, 1, 1, 1, 2, 2, 2, 2],
       [1, 1, 1, 1, 2, 2, 2, 2]])

In [29]:
arr = np.arange(20).reshape(2,10)
arr 

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19]])

In [31]:
np.split(arr,2, axis = 0)

[array([[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]]),
 array([[10, 11, 12, 13, 14, 15, 16, 17, 18, 19]])]

In [34]:
np.split(arr,5, axis = 1)

[array([[ 0,  1],
        [10, 11]]),
 array([[ 2,  3],
        [12, 13]]),
 array([[ 4,  5],
        [14, 15]]),
 array([[ 6,  7],
        [16, 17]]),
 array([[ 8,  9],
        [18, 19]])]

In [35]:
np.split(arr,5, axis = 1)

[array([[ 0,  1],
        [10, 11]]),
 array([[ 2,  3],
        [12, 13]]),
 array([[ 4,  5],
        [14, 15]]),
 array([[ 6,  7],
        [16, 17]]),
 array([[ 8,  9],
        [18, 19]])]

In [36]:
np.split(arr,[5], axis = 1)

[array([[ 0,  1,  2,  3,  4],
        [10, 11, 12, 13, 14]]),
 array([[ 5,  6,  7,  8,  9],
        [15, 16, 17, 18, 19]])]

In [37]:
np.split(arr,[2,5,7], axis = 1)

[array([[ 0,  1],
        [10, 11]]),
 array([[ 2,  3,  4],
        [12, 13, 14]]),
 array([[ 5,  6],
        [15, 16]]),
 array([[ 7,  8,  9],
        [17, 18, 19]])]

In [38]:
big_arr =np.arange(1e6) 


In [40]:
%timeit sum(big_arr)

92.2 ms ± 4.92 ms per loop (mean ± std. dev. of 7 runs, 10 loops each)


In [41]:
%timeit np.sum(big_arr)

1.85 ms ± 28.8 μs per loop (mean ± std. dev. of 7 runs, 1,000 loops each)


In [46]:
a = np.array([1,2,3])
b = np.array([[1],[3]])
print(a.shape, b.shape)
a+b 

(3,) (2, 1)


array([[2, 3, 4],
       [4, 5, 6]])

In [47]:
np.random.seed(0)
x = np.random.randint(10,size=(3,4))
print(x)

[[5 0 3 3]
 [7 9 3 5]
 [2 4 7 6]]


In [49]:
#1 
np.sum(x>8)

np.int64(1)

In [50]:
x==3 #mask or boolean index

array([[False, False,  True,  True],
       [False, False,  True, False],
       [False, False, False, False]])

In [52]:
#2
np.sum(x==3)

np.int64(3)

In [54]:
#3
np.sum(x[x>3])

np.int64(43)

In [57]:
#4
x[x%2==1].prod()

np.int64(297675)

In [ ]:
#5